@GrapesTl_HostAddress = https://localhost:44305

GET {{GrapesTl_HostAddress}}/api/RolePermission/permission
//Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI3NzNiZDJjNy00NDY3LTQ5ZDUtYWVlYy1kYzAzOTMzNmZmYzAiLCJzdWIiOiI5MDkwOSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkNoaW1idWsgQWRtaW4iLCJ1cmwiOiJDaGltYnVrIEFkbWluIiwiZXhwIjoxNzIxNTQwNzU5LCJpc3MiOiJodHRwOi8vdW1vamEuR3JhcGVzVGwuY29tIiwiYXVkIjoiaHR0cDovL3Vtb2phLkdyYXBlc1RsLmNvbSJ9.2jzZXwbeC3SD5X5XcqoRvjlO-zTOFfrDUDxbhvyg52c"

###

GET {{GrapesTl_HostAddress}}/api/rolepermission/rolepermission
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI1Yjg2MmZiMC03M2Y5LTRmNmYtOWUxZC1iNjlmZjQ1OTE0MmYiLCJzdWIiOiI5MDkwOSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkNoaW1idWsgQWRtaW4iLCJ1cmwiOiJDaGltYnVrIEFkbWluIiwiZXhwIjoxNzIxNTU5MDE4LCJpc3MiOiJodHRwOi8vdW1vamEuR3JhcGVzVGwuY29tIiwiYXVkIjoiaHR0cDovL3Vtb2phLkdyYXBlc1RsLmNvbSJ9.K6pyFXS7YGpL_4_Cxf-YIjgfUZVKwMxGPpNXQwvbNxE
Accept: application/json
###
