namespace GrapesTl.Models;

public class AuditChecklist
{
    public string ChecklistId { get; set; }
    public string AuditId { get; set; }
    public int QuestionId { get; set; }
    public string TestResults { get; set; }
    public string TestConclusion { get; set; }
    public string TestEvidences { get; set; }
    public string AuditArea { get; set; }
    public string Questionnaire { get; set; }
    public string AuditTestSteps { get; set; }

}

public class AuditChecklistUpdate
{
    public string AuditId { get; set; }
    public string TestResults1 { get; set; }
    public string TestConclusion1 { get; set; }
    public string TestEvidences1 { get; set; }
    public string TestResults2 { get; set; }
    public string TestConclusion2 { get; set; }
    public string TestEvidences2 { get; set; }
    public string TestResults3 { get; set; }
    public string TestConclusion3 { get; set; }
    public string TestEvidences3 { get; set; }
    public string TestResults4 { get; set; }
    public string TestConclusion4 { get; set; }
    public string TestEvidences4 { get; set; }
    public string TestResults5 { get; set; }
    public string TestConclusion5 { get; set; }
    public string TestEvidences5 { get; set; }
    public string TestResults6 { get; set; }
    public string TestConclusion6 { get; set; }
    public string TestEvidences6 { get; set; }
    public string TestResults7 { get; set; }
    public string TestConclusion7 { get; set; }
    public string TestEvidences7 { get; set; }
    public string TestResults8 { get; set; }
    public string TestConclusion8 { get; set; }
    public string TestEvidences8 { get; set; }
    public string TestResults9 { get; set; }
    public string TestConclusion9 { get; set; }
    public string TestEvidences9 { get; set; }
    public string TestResults10 { get; set; }
    public string TestConclusion10 { get; set; }
    public string TestEvidences10 { get; set; }
    public string TestResults11 { get; set; }
    public string TestConclusion11 { get; set; }
    public string TestEvidences11 { get; set; }
    public string TestResults12 { get; set; }
    public string TestConclusion12 { get; set; }
    public string TestEvidences12 { get; set; }
    public string TestResults13 { get; set; }
    public string TestConclusion13 { get; set; }
    public string TestEvidences13 { get; set; }
    public string TestResults14 { get; set; }
    public string TestConclusion14 { get; set; }
    public string TestEvidences14 { get; set; }
    public string TestResults15 { get; set; }
    public string TestConclusion15 { get; set; }
    public string TestEvidences15 { get; set; }
    public string TestResults16 { get; set; }
    public string TestConclusion16 { get; set; }
    public string TestEvidences16 { get; set; }
    public string TestResults17 { get; set; }
    public string TestConclusion17 { get; set; }
    public string TestEvidences17 { get; set; }
    public string TestResults18 { get; set; }
    public string TestConclusion18 { get; set; }
    public string TestEvidences18 { get; set; }
    public string TestResults19 { get; set; }
    public string TestConclusion19 { get; set; }
    public string TestEvidences19 { get; set; }
    public string TestResults20 { get; set; }
    public string TestConclusion20 { get; set; }
    public string TestEvidences20 { get; set; }
    public string TestResults21 { get; set; }
    public string TestConclusion21 { get; set; }
    public string TestEvidences21 { get; set; }
    public string TestResults22 { get; set; }
    public string TestConclusion22 { get; set; }
    public string TestEvidences22 { get; set; }
    public string TestResults23 { get; set; }
    public string TestConclusion23 { get; set; }
    public string TestEvidences23 { get; set; }
    public string TestResults24 { get; set; }
    public string TestConclusion24 { get; set; }
    public string TestEvidences24 { get; set; }
    public string TestResults25 { get; set; }
    public string TestConclusion25 { get; set; }
    public string TestEvidences25 { get; set; }
    public string TestResults26 { get; set; }
    public string TestConclusion26 { get; set; }
    public string TestEvidences26 { get; set; }
    public string TestResults27 { get; set; }
    public string TestConclusion27 { get; set; }
    public string TestEvidences27 { get; set; }
    public string TestResults28 { get; set; }
    public string TestConclusion28 { get; set; }
    public string TestEvidences28 { get; set; }
    public string TestResults29 { get; set; }
    public string TestConclusion29 { get; set; }
    public string TestEvidences29 { get; set; }
    public string TestResults30 { get; set; }
    public string TestConclusion30 { get; set; }
    public string TestEvidences30 { get; set; }
    public string TestResults31 { get; set; }
    public string TestConclusion31 { get; set; }
    public string TestEvidences31 { get; set; }
    public string TestResults32 { get; set; }
    public string TestConclusion32 { get; set; }
    public string TestEvidences32 { get; set; }
    public string TestResults33 { get; set; }
    public string TestConclusion33 { get; set; }
    public string TestEvidences33 { get; set; }
    public string TestResults34 { get; set; }
    public string TestConclusion34 { get; set; }
    public string TestEvidences34 { get; set; }
    public string TestResults35 { get; set; }
    public string TestConclusion35 { get; set; }
    public string TestEvidences35 { get; set; }
    public string TestResults36 { get; set; }
    public string TestConclusion36 { get; set; }
    public string TestEvidences36 { get; set; }
    public string TestResults37 { get; set; }
    public string TestConclusion37 { get; set; }
    public string TestEvidences37 { get; set; }
    public string TestResults38 { get; set; }
    public string TestConclusion38 { get; set; }
    public string TestEvidences38 { get; set; }
    public string TestResults39 { get; set; }
    public string TestConclusion39 { get; set; }
    public string TestEvidences39 { get; set; }
    public string TestResults40 { get; set; }
    public string TestConclusion40 { get; set; }
    public string TestEvidences40 { get; set; }
    public string TestResults41 { get; set; }
    public string TestConclusion41 { get; set; }
    public string TestEvidences41 { get; set; }
    public string TestResults42 { get; set; }
    public string TestConclusion42 { get; set; }
    public string TestEvidences42 { get; set; }
    public string TestResults43 { get; set; }
    public string TestConclusion43 { get; set; }
    public string TestEvidences43 { get; set; }
    public string TestResults44 { get; set; }
    public string TestConclusion44 { get; set; }
    public string TestEvidences44 { get; set; }
    public string TestResults45 { get; set; }
    public string TestConclusion45 { get; set; }
    public string TestEvidences45 { get; set; }
    public string TestResults46 { get; set; }
    public string TestConclusion46 { get; set; }
    public string TestEvidences46 { get; set; }
    public string TestResults47 { get; set; }
    public string TestConclusion47 { get; set; }
    public string TestEvidences47 { get; set; }
    public string TestResults48 { get; set; }
    public string TestConclusion48 { get; set; }
    public string TestEvidences48 { get; set; }
    public string TestResults49 { get; set; }
    public string TestConclusion49 { get; set; }
    public string TestEvidences49 { get; set; }
    public string TestResults50 { get; set; }
    public string TestConclusion50 { get; set; }
    public string TestEvidences50 { get; set; }
    public string TestResults51 { get; set; }
    public string TestConclusion51 { get; set; }
    public string TestEvidences51 { get; set; }
    public string TestResults52 { get; set; }
    public string TestConclusion52 { get; set; }
    public string TestEvidences52 { get; set; }
    public string TestResults53 { get; set; }
    public string TestConclusion53 { get; set; }
    public string TestEvidences53 { get; set; }
    public string TestResults54 { get; set; }
    public string TestConclusion54 { get; set; }
    public string TestEvidences54 { get; set; }
    public string TestResults55 { get; set; }
    public string TestConclusion55 { get; set; }
    public string TestEvidences55 { get; set; }
    public string TestResults56 { get; set; }
    public string TestConclusion56 { get; set; }
    public string TestEvidences56 { get; set; }
    public string TestResults57 { get; set; }
    public string TestConclusion57 { get; set; }
    public string TestEvidences57 { get; set; }
    public string TestResults58 { get; set; }
    public string TestConclusion58 { get; set; }
    public string TestEvidences58 { get; set; }
    public string TestResults59 { get; set; }
    public string TestConclusion59 { get; set; }
    public string TestEvidences59 { get; set; }
    public string TestResults60 { get; set; }
    public string TestConclusion60 { get; set; }
    public string TestEvidences60 { get; set; }
    public string TestResults61 { get; set; }
    public string TestConclusion61 { get; set; }
    public string TestEvidences61 { get; set; }
    public string TestResults62 { get; set; }
    public string TestConclusion62 { get; set; }
    public string TestEvidences62 { get; set; }
    public string TestResults63 { get; set; }
    public string TestConclusion63 { get; set; }
    public string TestEvidences63 { get; set; }
    public string TestResults64 { get; set; }
    public string TestConclusion64 { get; set; }
    public string TestEvidences64 { get; set; }
    public string TestResults65 { get; set; }
    public string TestConclusion65 { get; set; }
    public string TestEvidences65 { get; set; }
    public string TestResults66 { get; set; }
    public string TestConclusion66 { get; set; }
    public string TestEvidences66 { get; set; }
    public string TestResults67 { get; set; }
    public string TestConclusion67 { get; set; }
    public string TestEvidences67 { get; set; }
    public string TestResults68 { get; set; }
    public string TestConclusion68 { get; set; }
    public string TestEvidences68 { get; set; }
    public string TestResults69 { get; set; }
    public string TestConclusion69 { get; set; }
    public string TestEvidences69 { get; set; }
    public string TestResults70 { get; set; }
    public string TestConclusion70 { get; set; }
    public string TestEvidences70 { get; set; }
    public string TestResults71 { get; set; }
    public string TestConclusion71 { get; set; }
    public string TestEvidences71 { get; set; }
    public string TestResults72 { get; set; }
    public string TestConclusion72 { get; set; }
    public string TestEvidences72 { get; set; }
    public string TestResults73 { get; set; }
    public string TestConclusion73 { get; set; }
    public string TestEvidences73 { get; set; }
    public string TestResults74 { get; set; }
    public string TestConclusion74 { get; set; }
    public string TestEvidences74 { get; set; }
    public string TestResults75 { get; set; }
    public string TestConclusion75 { get; set; }
    public string TestEvidences75 { get; set; }
    public string TestResults76 { get; set; }
    public string TestConclusion76 { get; set; }
    public string TestEvidences76 { get; set; }
    public string TestResults77 { get; set; }
    public string TestConclusion77 { get; set; }
    public string TestEvidences77 { get; set; }
    public string TestResults78 { get; set; }
    public string TestConclusion78 { get; set; }
    public string TestEvidences78 { get; set; }

}
